# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_imag', models.FileField(default=b'null', upload_to=b'./upload/')),
                ('price', models.IntegerField(default=1)),
                ('play', models.CharField(choices=[(b'p', b'play'), (b'n', b'not play')], default=b'n', max_length=1)),
            ],
        ),
    ]
